### ISSUE TITLE
Crash:  java.lang.IllegalArgumentException: No model for layer geode_plus:wrappist_pedestal#main

### ISSUE THREAD

**Issue by DissonantSynth** [ChorusTeam/geode-plus#6]
Minecraft Version: 1.20.1
Forge Version: 47.3.0
Mod Version: 1.2.5

```
The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: No model for layer geode_plus:wrappist_pedestal#main
Exit Code: -1
```

[crash-2024-06-24_23.35.48-client.txt](https://github.com/user-attachments/files/15961580/crash-2024-06-24_23.35.48-client.txt)
[latest.log](https://github.com/user-attachments/files/15961588/latest.log)

**Comment by YeoXuHang** [comment]
This issue cannot be solved, report it on https://github.com/Sinytra/Connector/issues

**Comment by Secondyou** [comment]
same problem at forge but little bit different

**Comment by WineAndCyanide** [comment]
I also have the same problem, just don't use Sinytra Connector.
